categories:
  - title: '✨ Enhancements'
    labels:
      - 'enhancement'
      - 'feature'
  - title: '🐞 Bug Fixes'
    labels:
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    label:
      - 'chore'
      - 'documentation'
      - 'dependencies'
template: |
  <!-- Update Template --> 

  ## Changes

  $CHANGES
  
  <!-- sparkle:edSignature=xxxxx -->
