disabled_rules:
  - todo
  - trailing_comma
  - nesting

type_name:
  excluded:
    - ID

identifier_name:
  excluded:
    - id
    - vc

# paths to ignore during linting.
excluded:
  - .build # Where Swift Package Manager checks out dependency sources
  
opt_in_rules:
  - empty_count
  - closure_spacing
  - contains_over_first_not_nil
  - missing_docs
#  - implicit_return
  - modifier_order
  - convenience_type
  - pattern_matching_keywords

custom_rules:
  spaces_over_tabs:
    included: ".*\\.swift"
    name: "Spaces over Tabs"
    regex: "\t"
    message: "Prefer spaces for indents over tabs. See Xcode setting: 'Text Editing' -> 'Indentation'"
    severity: warning
