name: 🐞 Bug report
description: Something is not working as expected.
title: 🐞 YOUR_DESCRIPTION
labels: bug

body:
  - type: textarea
    attributes:
      label: Description
      description: >-
        A clear and concise description of what the bug is.
    validations:
      required: true
      
  - type: textarea
    attributes:
      label: To Reproduce
      description: >-
        Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behavior
      description: >-
        A clear and concise description of what you expected to happen.
    validations:
      required: true
      
  - type: textarea
    attributes:
      label: Version information
      description: >-
         click on the version number on the welcome screen
      value: |
        CodeEdit: [e.g. 1.0]
        Hash: [e.g. 87a5b3f4c18238c0d06cbfce595e1ca9b11cfd8e]
        MacOS: [e.g. 12.3.0]
        Xcode: [e.g. 13.3]
    validations:
      required: true
      
  - type: textarea
    attributes:
      label: Additional context
      description: >-
        Add any other context about the problem here.