name: ðŸž Bug report
description: Something is not working as expected.
title: ðŸž - YOUR_DESCRIPTION
labels: bug

body:
  - type: textarea
    attributes:
      label: Description
      description: >-
        A clear and concise description of what the bug is.
    validations:
      required: true
      
  - type: textarea
    attributes:
      label: To Reproduce
      description: >-
        Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behavior
      description: >-
        A clear and concise description of what you expected to happen.

  - type: input
    attributes:
      label: CodeEdit version
      value: 1.0
    validations:
      required: true

  - type: input
    attributes:
      label: macOS version
      value: 12.3
    validations:
      required: true

  - type: input
    attributes:
      label: Xcode version
      value: 13.3
    validations:
      required: false
      
  - type: input
    attributes:
      label: Commit hash
    validations:
      required: false
      
  - type: textarea
    attributes:
      label: Additional context
      description: >-
        Add any other context about the problem here.