name: 🐞 Bug report
description: Something is not working as expected.
title: 🐞 <bug title>
labels: bug

body:
  - type: textarea
    attributes:
      label: Description
      placeholder: >-
        A clear and concise description of what the bug is...
    validations:
      required: true
      
  - type: textarea
    attributes:
      label: To Reproduce
      description: >-
        Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behavior
      description: >-
        A clear and concise description of what you expected to happen.
    validations:
      required: true
      
  - type: textarea
    attributes:
      label: Version information
      description: >-
         click on the version number on the welcome screen
      value: |
        CodeEdit: [e.g. 1.0]
        macOS: [e.g. 13.2.1]
        Xcode: [e.g. 14.2]
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional context
      placeholder: >-
        Any other context or considerations about the bug...
      
  - type: textarea
    attributes:
      label: Screenshots
      placeholder: >-
        If applicable, please provide relevant screenshots or screen recordings...
