name: Build and Upload Artifact

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  build_upload:
    name: Build and Upload Artifact
    runs-on: macos-12
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build CodeEdit
        # 'CODE_SIGN_IDENTITY=-' overrides code signing to ad-hoc. To sign with a developer account, see below. 
        # https://docs.github.com/en/actions/deployment/deploying-xcode-applications/installing-an-apple-certificate-on-macos-runners-for-xcode-development
        run: xcodebuild -workspace CodeEdit.xcworkspace -scheme CodeEdit -configuration Release -archivePath CodeEdit.xcarchive archive CODE_SIGN_IDENTITY=-
      - name: Create CodeEdit.dmg
        run: |
          mkdir CodeEdit_dmg
          cp -r CodeEdit.xcarchive/Products/Applications/CodeEdit.app CodeEdit_dmg
          hdiutil create -srcfolder CodeEdit_dmg -volname CodeEdit -format ULMO CodeEdit.dmg
      - name: Upload CodeEdit.dmg
        uses: actions/upload-artifact@v3.1.0
        with:
          name: CodeEdit.dmg
          path: CodeEdit.dmg
