name: Build and Release

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  build_upload:
    name: Build and Release
    runs-on: macos-12
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build CodeEdit
        # 'CODE_SIGN_IDENTITY=-' overrides code signing to ad-hoc. To sign with a developer account, see below. 
        # https://docs.github.com/en/actions/deployment/deploying-xcode-applications/installing-an-apple-certificate-on-macos-runners-for-xcode-development
        run: xcodebuild -workspace CodeEdit.xcworkspace -scheme CodeEdit -configuration Release -archivePath CodeEdit.xcarchive archive CODE_SIGN_IDENTITY=-
      - name: Create CodeEdit.dmg
        run: |
          REV=$(git rev-parse --short HEAD)
          echo "REV=$REV" >> $GITHUB_ENV
          mkdir "CodeEdit-$REV"
          cp -r CodeEdit.xcarchive/Products/Applications/CodeEdit.app "CodeEdit-$REV"
          hdiutil create -srcfolder CodeEdit-$REV -volname CodeEdit -format ULMO "CodeEdit-$REV.dmg"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: CodeEdit-${{ env.REV }}.dmg
          name: CodeEdit-${{ env.REV }}
          prerelease: true
          generate_release_notes: true
