name: CI - Pre Release
on:
  workflow_dispatch:
jobs:
  swiftlint:
    name: SwiftLint
    uses: ./.github/workflows/lint.yml
    secrets: inherit
  test:
    name: Testing CodeEdit
    needs: swiftlint
    uses: ./.github/workflows/tests.yml
    secrets: inherit
  deploy:
    if: github.repository_owner == 'CodeEditApp'
    name: Deploying CodeEdit [Prerelease]
    needs: [swiftlint, test]
    uses: ./.github/workflows/pre-release.yml
    secrets: inherit
  ReleaseDrafter:
    name: Release Drafter
    needs: [swiftlint, test, deploy]
    uses: ./.github/workflows/release-drafter.yml
